version: "3.6"

services:
  nats:
    image: "nats-streaming:0.9.2"
    restart: "always"
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "meower"
      POSTGRES_USER: "meower"
      POSTGRES_PASSWORD: "123456"
